-- Data from AreaTable.dbc, resolved live via C_Map.GetAreaInfo instead of a
-- hand-maintained name table -- this always matches whatever era/locale
-- this client actually has data for, instead of a stale scraped snapshot.
Twm_areadb = setmetatable({}, {
    __index = function(t, id)
        local name = C_Map.GetAreaInfo(id)
        if(name) then
            rawset(t, id, name)
        end
        return name
    end,
})


-- ID mapped to AreaTable.dbc;
-- Coordination from WorldMapArea.dbc
-- Azeroth/Kalimdor/Expansion01 blocks live in mapdata_continents.lua
-- (generated by scripts/gen_mapareas.js, loads right after this file).
Twm_mapareas = {}

-- Capital/major city uiMapIDs (WorldMapFrame zoom-in sub-maps), hand-collected
-- via C_Map.GetMapChildrenInfo since Blizzard's map hierarchy gives no
-- type/parent-based way to tell a city map apart from a real outdoor zone --
-- see WorldMapOverlay.lua's city-map-tiles option.
Twm_CityMapIDs = {
    [1453] = true, -- Stormwind City
    [1455] = true, -- Ironforge
    [1458] = true, -- Undercity
    [1954] = true, -- Silvermoon City
    [1454] = true, -- Orgrimmar
    [1456] = true, -- Thunder Bluff
    [1457] = true, -- Darnassus
    [1947] = true, -- The Exodar
    [1955] = true, -- Shattrath City
}


