-- Client-agnostic: shared by every flavor's toc (Vanilla/TBC/Mists/...).
-- Flavor-specific Twm_CityMapIDs lives in Data_<Flavor>/mapdata_continents.lua
-- (generated by scripts/gen_mapareas.js from Twm_CapitalAreaIDs below).

-- Data from AreaTable.dbc, resolved live via C_Map.GetAreaInfo instead of a
-- hand-maintained name table -- this always matches whatever era/locale
-- this client actually has data for, instead of a stale scraped snapshot.
Twm_areadb = setmetatable({}, {
    __index = function(t, id)
        local name = C_Map.GetAreaInfo(id)
        if(name) then
            rawset(t, id, name)
        end
        return name
    end,
})


-- ID mapped to AreaTable.dbc;
-- Coordination from WorldMapArea.dbc
-- Azeroth/Kalimdor/Expansion01 (etc.) blocks live in
-- Data_<Flavor>/mapdata_continents.lua (generated by scripts/gen_mapareas.js,
-- loads right after this file).
Twm_mapareas = {}

-- Hardcoded capital-city AreaIDs (AreaTable.dbc's own AreaID, from
-- Wowhead's capital-city list) -- neither AreaTable nor AreaPOI's own
-- flags reliably separate "capital" from "city" across every flavor (see
-- scripts/README.md's Twm_poi_areas notes), so this is hand-maintained
-- instead. AreaID is stable across the whole game's history (unlike
-- WorldMapFrame's uiMapID, which gets renumbered per expansion), so one
-- flavor-agnostic table here covers Vanilla/TBC/Mists and any future
-- flavor without needing to be re-collected. Not every entry exists in
-- every flavor this addon supports; harmless if absent.
-- scripts/gen_mapareas.js reads this table directly (parsed from this
-- file) to derive each flavor's own Twm_CityMapIDs -- keep this the only
-- place this list is maintained.
Twm_CapitalAreaIDs = {
    [1519] = "Stormwind City",
    [1637] = "Orgrimmar",
    [1657] = "Darnassus",
    [1638] = "Thunder Bluff",
    [1537] = "Ironforge",
    [1497] = "Undercity",
    [3703] = "Shattrath City",
    [3487] = "Silvermoon City",
    [3557] = "The Exodar",
    [4395] = "Dalaran (Northrend)",
    [7502] = "Dalaran (Broken Isles)",
    [6142] = "Shrine of Seven Stars",
    [8568] = "Boralus",
    [8670] = "Dazar'alor",
    [7332] = "Stormshield",
    [7333] = "Warspear",
    [10565] = "Oribos",
    [13862] = "Valdrakken",
    [14771] = "Dornogal",
}
